spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/businessmanager?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #https://blog.csdn.net/elim168/article/details/91393864
    #https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
    druid:
      url: jdbc:mysql://127.0.0.1:3306/businessmanager?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      min-idle: 5
      initial-size: 5
      max-wait: 10000
      validation-query: select 1
      validation-query-timeout: 2
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      filters: stat,wall
  jpa:
    database: MYSQL
    show-sql: true
mybatis:
  mapper-locations: mapping/*Mapping.xml
  type-aliases-package: com.rpt.system.bean
bloom:
  filter:
    expectedInsertions: 1000
    fpp: 0.001F
server:
  port: 8061 #tomcat端口号





#dubbo:
#  application:
#    name: rpt-center
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    # 读者请自行更改zookeeper地址
#    protocol: zookeeper
#    check: false
#  scan:
#    base-packages: com.rpt.system.service
#  monitor:
#    protocol: register
#  consumer:
#    check: false
#    timeout: 3000
#  protocol:
#    name: dubbo
#    port: 30003
#  protocols:
#    p1:
#      id: dubbo1
#      name: dubbo
#      port: 20881
#      host: 0.0.0.0

#dubbo:
#  application:
#    name: rpt-center
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    # 读者请自行更改zookeeper地址
#    protocol: zookeeper
#    check: false
#  protocol:
#    name: dubbo
#    port: 30003
#  monitor:
#    protocol: register
#  consumer:
#    check: false
#    timeout: 3000
#

